version: '2'

services:
  db:
    image: postgres:12-alpine
  web:
    image: rails-devise-jwt
    links:
      - db
    volumes:
      - .:/usr/src/app
    environment:
      DATABASE_URL: postgres://postgres@db:5432/rails-devise-jwt?pool=25&encoding=unicode&schema_search_path=public

