DEVISE_JWT_SECRET_KEY: RANDOM_SECRET
REDIS_URL: redis://localhost:6379
QINIU_ENABLED: 'yes'
QINIU_ACCESS_KEY: empty
QINIU_SECRET_KEY: empty
QINIU_BUCKET: empty
QINIU_HOST: empty
WECHAT_APP_ID: empty
WECHAT_APP_SECRET: empty
WECHAT_APP_TOKEN: empty
WECHAT_APP_ENCODING_AES_KEY: empty
