DEVISE_JWT_SECRET_KEY: RANDOM_SECRET
REDIS_URL: redis://localhost:6379/1
QINIU_ENABLED: 'yes'
QINIU_ACCESS_KEY: EMPTY
QINIU_SECRET_KEY: EMPTY
QINIU_BUCKET: EMPTY
QINIU_HOST: EMPTY
WECHAT_APP_ID: EMPTY
WECHAT_APP_SECRET: EMPTY
WECHAT_APP_TOKEN: EMPTY
WECHAT_APP_ENCODING_AES_KEY: EMPTY
